"""Cancel-and-route rules for SubscriptionPaymentRequest (2026-05-29).

End-to-end behaviour the user described in the cancel-and-route
batch design:

  C1. Farmer sees who the payment is pending with + countdown
      → covered by `pending_payment_from` shape change in
      /farmer/my-subscriptions (asserted indirectly via the model).
  C2. Farmer can cancel anytime; delegate is FCM-notified.
  C3. Subscription-cancel is BLOCKED while a payment is pending.
  C4. Facilitator's decline notifies farmer (decoration in
      orders/router.py:facilitator_decline_payment).
  C5. 24h auto-expiry sweep — covered by
      tests/test_phase_payment_request_expiry_task.py (separate file
      because it exercises the celery-task entry point).
  C6. Facilitator's /facilitator/payment-requests payload is now
      decorated; that's covered by an integration check in this file.
  C8. Single PENDING per subscription — second delegate attempt
      is rejected.

The 24h expiry sweep is in
`tests/test_phase_payment_request_expiry_task.py`.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

import pytest
from fastapi import HTTPException
from sqlalchemy import select

from app.modules.advisory.models import Package
from app.modules.clients.models import Client
from app.modules.clients.models import ClientPromoter
from app.modules.clients.router import register_promoter
from app.modules.orders.router import (
    facilitator_decline_payment,
    facilitator_payment_requests,
)
from app.modules.subscriptions.models import (
    Subscription, SubscriptionPaymentRequest, SubscriptionStatus,
)
from app.modules.subscriptions.router import (
    PaymentDelegateRequest,
    cancel_delegation, delegate_payment, my_subscriptions, unsubscribe,
)
from tests.conftest import requires_docker
from tests.factories import (
    make_client, make_package, make_self_registered_user,
    make_subscription, make_user,
)


async def _seed(db, *, delegate_phone="+919900400099"):
    """Make a farmer + delegate (Facilitator onboarded at the client) +
    WAITLISTED sub. The delegate is `register_promoter`-onboarded so
    `_assert_active_facilitator` passes when the test exercises
    /facilitator/* endpoints. The delegate's phone is fixed because
    `delegate_payment` looks up the user by phone; the farmer's
    phone is auto-generated by the factory."""
    sa = await make_user(db, name="SA")
    client = await make_client(db)
    pkg = await make_package(db, client)
    farmer = await make_user(db, name="Farmer")
    delegate = await make_self_registered_user(
        db, phone=delegate_phone, role="FACILITATOR", name="Delegate",
    )
    sub = await make_subscription(
        db, farmer=farmer, client=client, package=pkg,
    )
    sub.status = SubscriptionStatus.WAITLISTED   # factory hardcodes ACTIVE
    await db.commit()
    # Re-read so the in-memory enum membership matches what
    # /farmer/my-subscriptions will see (a String(20) column read
    # back as a plain str, not the SubscriptionStatus enum
    # instance the test set in Python).
    await db.refresh(sub)

    await register_promoter(
        client_id=client.id,
        request={"phone": delegate_phone, "promoter_type": "FACILITATOR"},
        db=db, current_user=sa,
    )
    return client, pkg, farmer, delegate, sub


# ── C8: double-delegation is rejected ─────────────────────────────────────

@requires_docker
@pytest.mark.asyncio
async def test_second_delegation_while_pending_returns_409(db):
    _, _, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )

    with pytest.raises(HTTPException) as ei:
        await delegate_payment(
            subscription_id=sub.id,
            request=PaymentDelegateRequest(delegate_phone="+919900400099"),
            db=db, current_user=farmer,
        )
    assert ei.value.status_code == 409
    assert ei.value.detail["code"] == "payment_request_already_pending"


# ── C2: farmer cancels → request flips to CANCELLED ───────────────────────

@requires_docker
@pytest.mark.asyncio
async def test_farmer_cancel_flips_pending_to_cancelled(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    await cancel_delegation(
        subscription_id=sub.id, db=db, current_user=farmer,
    )

    pr = (await db.execute(
        select(SubscriptionPaymentRequest).where(
            SubscriptionPaymentRequest.subscription_id == sub.id,
        )
    )).scalar_one()
    assert pr.status == "CANCELLED"


# ── C2 follow-up: after cancel, a new delegation is allowed ───────────────

@requires_docker
@pytest.mark.asyncio
async def test_after_cancel_farmer_can_delegate_again(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    await cancel_delegation(
        subscription_id=sub.id, db=db, current_user=farmer,
    )
    out = await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    assert out["detail"] == "Payment request sent"


# ── C3: unsubscribe is blocked while a payment is pending ─────────────────

@requires_docker
@pytest.mark.asyncio
async def test_unsubscribe_blocked_when_payment_pending(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )

    with pytest.raises(HTTPException) as ei:
        await unsubscribe(
            subscription_id=sub.id, db=db, current_user=farmer,
        )
    assert ei.value.status_code == 409
    assert ei.value.detail["code"] == "pending_payment_blocks_unsubscribe"


# ── C3 follow-up: after cancelling the payment, unsubscribe works ─────────

@requires_docker
@pytest.mark.asyncio
async def test_unsubscribe_works_after_cancel(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    await cancel_delegation(
        subscription_id=sub.id, db=db, current_user=farmer,
    )
    out = await unsubscribe(
        subscription_id=sub.id, db=db, current_user=farmer,
    )
    assert out["status"] == SubscriptionStatus.CANCELLED


# ── C1: /farmer/my-subscriptions surfaces pending_payment_from richly ────

@requires_docker
@pytest.mark.asyncio
async def test_pending_payment_from_carries_phone_and_hours_remaining(db):
    _, _, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    subs = await my_subscriptions(db=db, current_user=farmer)
    pending = next(s for s in subs if s["id"] == sub.id)["pending_payment_from"]
    assert pending is not None
    assert pending["user_id"] == delegate.id
    assert pending["name"] == delegate.name
    assert pending["phone"] == delegate.phone
    assert "payment_request_id" in pending
    # 24h request just created — should be 23 or 24 hours remaining,
    # never negative.
    assert 22 <= pending["hours_remaining"] <= 24


# ── C6: /facilitator/payment-requests payload is decorated ────────────────

@requires_docker
@pytest.mark.asyncio
async def test_facilitator_payment_requests_is_decorated(db):
    client, pkg, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )

    out = await facilitator_payment_requests(db=db, current_user=delegate)
    assert len(out) == 1
    row = out[0]
    assert row["farmer_user_id"] == farmer.id
    assert row["farmer_name"] == farmer.name
    assert row["farmer_phone"] == farmer.phone
    assert row["package_id"] == pkg.id
    assert row["package_name"] == pkg.name
    assert row["amount"] == 199.0
    assert row["status"] == "PENDING"
    assert 22 <= row["hours_remaining"] <= 24


# ── C4: facilitator decline marks DECLINED + only the right row ───────────

@requires_docker
@pytest.mark.asyncio
async def test_facilitator_decline_flips_only_pending_row(db):
    _, _, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    pr_id = (await db.execute(
        select(SubscriptionPaymentRequest.id).where(
            SubscriptionPaymentRequest.subscription_id == sub.id,
        )
    )).scalar_one()

    out = await facilitator_decline_payment(
        request_id=pr_id, db=db, current_user=delegate,
    )
    assert out["status"] == "DECLINED"

    # Replaying the decline on the same (now-non-pending) row 404s.
    with pytest.raises(HTTPException) as ei:
        await facilitator_decline_payment(
            request_id=pr_id, db=db, current_user=delegate,
        )
    assert ei.value.status_code == 404


# ── 2026-05-30: target-must-be-facilitator-or-dealer validation ───────────

@requires_docker
@pytest.mark.asyncio
async def test_delegate_refused_when_target_not_facilitator_or_dealer(db):
    """User report 2026-05-30: rows were getting created with a
    non-onboarded target; the target's PWA Payments tab then 403'd
    on _assert_active_facilitator so they never saw the request.
    The farmer thought they had successfully asked someone. Add a
    create-time guard so the failure surfaces immediately on the
    farmer's screen with an actionable 422.
    """
    sa = await make_user(db, name="SA")
    client = await make_client(db)
    pkg = await make_package(db, client)
    farmer = await make_user(db, name="Farmer")
    # Bystander — a real user but with NO ClientPromoter row of any
    # kind. The farmer enters their phone, the lookup succeeds, but
    # the new guard refuses.
    bystander = await make_self_registered_user(
        db, phone="+919812341234", role="FACILITATOR", name="Bystander",
    )
    sub = await make_subscription(db, farmer=farmer, client=client, package=pkg)
    sub.status = SubscriptionStatus.WAITLISTED
    await db.commit()
    await db.refresh(sub)

    with pytest.raises(HTTPException) as ei:
        await delegate_payment(
            subscription_id=sub.id,
            request=PaymentDelegateRequest(delegate_phone="+919812341234"),
            db=db, current_user=farmer,
        )
    assert ei.value.status_code == 422
    assert ei.value.detail["code"] == "target_not_facilitator_or_dealer"

    # And no row was created.
    rows = (await db.execute(
        select(SubscriptionPaymentRequest).where(
            SubscriptionPaymentRequest.subscription_id == sub.id,
        )
    )).scalars().all()
    assert rows == []


@requires_docker
@pytest.mark.asyncio
async def test_delegate_succeeds_when_target_is_facilitator_at_any_client(db):
    """Per user 2026-05-30: a Facilitator onboarding at any company
    is sufficient; the target doesn't need to also be designated as
    a Promoter. The existing _seed helper already onboards via
    `register_promoter` which writes status=ACTIVE — the create
    succeeds even though `is_promoter` defaults to False post-R9."""
    _, _, farmer, _, sub = await _seed(db)
    out = await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    assert out["detail"] == "Payment request sent"


@requires_docker
@pytest.mark.asyncio
async def test_delegate_refused_when_target_is_self(db):
    """Self-delegation guard. The PWA blocks before submit but the
    backend has its own guard so a direct API call can't bypass."""
    _, _, farmer, _, sub = await _seed(db)
    farmer.phone = "+919811112222"
    await db.commit()
    with pytest.raises(HTTPException) as ei:
        await delegate_payment(
            subscription_id=sub.id,
            request=PaymentDelegateRequest(delegate_phone="+919811112222"),
            db=db, current_user=farmer,
        )
    assert ei.value.status_code == 422
    assert ei.value.detail["code"] == "delegate_is_self"


# ── 2026-05-30: delegate-lookup (two-step Check → Send) ────────────────────

@requires_docker
@pytest.mark.asyncio
async def test_delegate_lookup_returns_name_roles_affiliations(db):
    """Happy path: phone resolves to an onboarded Facilitator; the
    response carries name, phone, roles list, and per-company
    affiliations so the PWA can render 'Ravi · Facilitator at <Co>'."""
    from app.modules.subscriptions.router import delegate_lookup
    _, _, farmer, _, _ = await _seed(db)

    out = await delegate_lookup(
        phone="+919900400099", db=db, current_user=farmer,
    )
    assert out["phone"] == "+919900400099"
    assert "FACILITATOR" in out["roles"]
    assert len(out["affiliations"]) >= 1
    assert out["affiliations"][0]["role"] == "FACILITATOR"
    assert out["affiliations"][0]["company_name"]


@requires_docker
@pytest.mark.asyncio
async def test_delegate_lookup_404s_for_unregistered_phone(db):
    from app.modules.subscriptions.router import delegate_lookup
    _, _, farmer, _, _ = await _seed(db)
    with pytest.raises(HTTPException) as ei:
        await delegate_lookup(
            phone="+919999999999", db=db, current_user=farmer,
        )
    assert ei.value.status_code == 404
    assert ei.value.detail["code"] == "phone_not_registered"


@requires_docker
@pytest.mark.asyncio
async def test_delegate_lookup_422s_when_not_facilitator_or_dealer(db):
    """Phone resolves to a real user but they have no ACTIVE
    Facilitator/Dealer ClientPromoter row anywhere — same code the
    POST endpoint uses, so the PWA can branch identically."""
    from app.modules.subscriptions.router import delegate_lookup
    _, _, farmer, _, _ = await _seed(db)
    # Bystander — real user, no promoter row.
    await make_self_registered_user(
        db, phone="+919812341234", role="FACILITATOR", name="Bystander",
    )
    await db.commit()

    with pytest.raises(HTTPException) as ei:
        await delegate_lookup(
            phone="+919812341234", db=db, current_user=farmer,
        )
    assert ei.value.status_code == 422
    assert ei.value.detail["code"] == "target_not_facilitator_or_dealer"


@requires_docker
@pytest.mark.asyncio
async def test_delegate_lookup_422s_when_target_is_self(db):
    from app.modules.subscriptions.router import delegate_lookup
    _, _, farmer, _, _ = await _seed(db)
    farmer.phone = "+919811112222"
    await db.commit()
    with pytest.raises(HTTPException) as ei:
        await delegate_lookup(
            phone="+919811112222", db=db, current_user=farmer,
        )
    assert ei.value.status_code == 422
    assert ei.value.detail["code"] == "delegate_is_self"
