"""Cancel-and-route rules for SubscriptionPaymentRequest (2026-05-29).

End-to-end behaviour the user described in the cancel-and-route
batch design:

  C1. Farmer sees who the payment is pending with + countdown
      → covered by `pending_payment_from` shape change in
      /farmer/my-subscriptions (asserted indirectly via the model).
  C2. Farmer can cancel anytime; delegate is FCM-notified.
  C3. Subscription-cancel is BLOCKED while a payment is pending.
  C4. Facilitator's decline notifies farmer (decoration in
      orders/router.py:facilitator_decline_payment).
  C5. 24h auto-expiry sweep — covered by
      tests/test_phase_payment_request_expiry_task.py (separate file
      because it exercises the celery-task entry point).
  C6. Facilitator's /facilitator/payment-requests payload is now
      decorated; that's covered by an integration check in this file.
  C8. Single PENDING per subscription — second delegate attempt
      is rejected.

The 24h expiry sweep is in
`tests/test_phase_payment_request_expiry_task.py`.
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

import pytest
from fastapi import HTTPException
from sqlalchemy import select

from app.modules.advisory.models import Package
from app.modules.clients.models import Client
from app.modules.clients.models import ClientPromoter
from app.modules.clients.router import register_promoter
from app.modules.orders.router import (
    facilitator_decline_payment,
    facilitator_payment_requests,
)
from app.modules.subscriptions.models import (
    Subscription, SubscriptionPaymentRequest, SubscriptionStatus,
)
from app.modules.subscriptions.router import (
    PaymentDelegateRequest,
    cancel_delegation, delegate_payment, my_subscriptions, unsubscribe,
)
from tests.conftest import requires_docker
from tests.factories import (
    make_client, make_package, make_self_registered_user,
    make_subscription, make_user,
)


async def _seed(db, *, delegate_phone="+919900400099"):
    """Make a farmer + delegate (Facilitator onboarded at the client) +
    WAITLISTED sub. The delegate is `register_promoter`-onboarded so
    `_assert_active_facilitator` passes when the test exercises
    /facilitator/* endpoints. The delegate's phone is fixed because
    `delegate_payment` looks up the user by phone; the farmer's
    phone is auto-generated by the factory."""
    sa = await make_user(db, name="SA")
    client = await make_client(db)
    pkg = await make_package(db, client)
    farmer = await make_user(db, name="Farmer")
    delegate = await make_self_registered_user(
        db, phone=delegate_phone, role="FACILITATOR", name="Delegate",
    )
    sub = await make_subscription(
        db, farmer=farmer, client=client, package=pkg,
    )
    sub.status = SubscriptionStatus.WAITLISTED   # factory hardcodes ACTIVE
    await db.commit()
    # Re-read so the in-memory enum membership matches what
    # /farmer/my-subscriptions will see (a String(20) column read
    # back as a plain str, not the SubscriptionStatus enum
    # instance the test set in Python).
    await db.refresh(sub)

    await register_promoter(
        client_id=client.id,
        request={"phone": delegate_phone, "promoter_type": "FACILITATOR"},
        db=db, current_user=sa,
    )
    return client, pkg, farmer, delegate, sub


# ── C8: double-delegation is rejected ─────────────────────────────────────

@requires_docker
@pytest.mark.asyncio
async def test_second_delegation_while_pending_returns_409(db):
    _, _, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )

    with pytest.raises(HTTPException) as ei:
        await delegate_payment(
            subscription_id=sub.id,
            request=PaymentDelegateRequest(delegate_phone="+919900400099"),
            db=db, current_user=farmer,
        )
    assert ei.value.status_code == 409
    assert ei.value.detail["code"] == "payment_request_already_pending"


# ── C2: farmer cancels → request flips to CANCELLED ───────────────────────

@requires_docker
@pytest.mark.asyncio
async def test_farmer_cancel_flips_pending_to_cancelled(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    await cancel_delegation(
        subscription_id=sub.id, db=db, current_user=farmer,
    )

    pr = (await db.execute(
        select(SubscriptionPaymentRequest).where(
            SubscriptionPaymentRequest.subscription_id == sub.id,
        )
    )).scalar_one()
    assert pr.status == "CANCELLED"


# ── C2 follow-up: after cancel, a new delegation is allowed ───────────────

@requires_docker
@pytest.mark.asyncio
async def test_after_cancel_farmer_can_delegate_again(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    await cancel_delegation(
        subscription_id=sub.id, db=db, current_user=farmer,
    )
    out = await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    assert out["detail"] == "Payment request sent"


# ── C3: unsubscribe is blocked while a payment is pending ─────────────────

@requires_docker
@pytest.mark.asyncio
async def test_unsubscribe_blocked_when_payment_pending(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )

    with pytest.raises(HTTPException) as ei:
        await unsubscribe(
            subscription_id=sub.id, db=db, current_user=farmer,
        )
    assert ei.value.status_code == 409
    assert ei.value.detail["code"] == "pending_payment_blocks_unsubscribe"


# ── C3 follow-up: after cancelling the payment, unsubscribe works ─────────

@requires_docker
@pytest.mark.asyncio
async def test_unsubscribe_works_after_cancel(db):
    _, _, farmer, _, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    await cancel_delegation(
        subscription_id=sub.id, db=db, current_user=farmer,
    )
    out = await unsubscribe(
        subscription_id=sub.id, db=db, current_user=farmer,
    )
    assert out["status"] == SubscriptionStatus.CANCELLED


# ── C1: /farmer/my-subscriptions surfaces pending_payment_from richly ────

@requires_docker
@pytest.mark.asyncio
async def test_pending_payment_from_carries_phone_and_hours_remaining(db):
    _, _, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    subs = await my_subscriptions(db=db, current_user=farmer)
    pending = next(s for s in subs if s["id"] == sub.id)["pending_payment_from"]
    assert pending is not None
    assert pending["user_id"] == delegate.id
    assert pending["name"] == delegate.name
    assert pending["phone"] == delegate.phone
    assert "payment_request_id" in pending
    # 24h request just created — should be 23 or 24 hours remaining,
    # never negative.
    assert 22 <= pending["hours_remaining"] <= 24


# ── C6: /facilitator/payment-requests payload is decorated ────────────────

@requires_docker
@pytest.mark.asyncio
async def test_facilitator_payment_requests_is_decorated(db):
    client, pkg, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )

    out = await facilitator_payment_requests(db=db, current_user=delegate)
    assert len(out) == 1
    row = out[0]
    assert row["farmer_user_id"] == farmer.id
    assert row["farmer_name"] == farmer.name
    assert row["farmer_phone"] == farmer.phone
    assert row["package_id"] == pkg.id
    assert row["package_name"] == pkg.name
    assert row["amount"] == 199.0
    assert row["status"] == "PENDING"
    assert 22 <= row["hours_remaining"] <= 24


# ── C4: facilitator decline marks DECLINED + only the right row ───────────

@requires_docker
@pytest.mark.asyncio
async def test_facilitator_decline_flips_only_pending_row(db):
    _, _, farmer, delegate, sub = await _seed(db)

    await delegate_payment(
        subscription_id=sub.id,
        request=PaymentDelegateRequest(delegate_phone="+919900400099"),
        db=db, current_user=farmer,
    )
    pr_id = (await db.execute(
        select(SubscriptionPaymentRequest.id).where(
            SubscriptionPaymentRequest.subscription_id == sub.id,
        )
    )).scalar_one()

    out = await facilitator_decline_payment(
        request_id=pr_id, db=db, current_user=delegate,
    )
    assert out["status"] == "DECLINED"

    # Replaying the decline on the same (now-non-pending) row 404s.
    with pytest.raises(HTTPException) as ei:
        await facilitator_decline_payment(
            request_id=pr_id, db=db, current_user=delegate,
        )
    assert ei.value.status_code == 404
