"""domain10_qr_codes

Revision ID: 3f543047d712
Revises: 9bc5043bd052
Create Date: 2026-05-01 14:33:01.175219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f543047d712'
down_revision: Union[str, Sequence[str], None] = '9bc5043bd052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer_brand_portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('brand_cosh_id', sa.String(length=200), nullable=True),
    sa.Column('variety_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_qr_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('brand_cosh_id', sa.String(length=200), nullable=True),
    sa.Column('variety_id', sa.String(length=36), nullable=True),
    sa.Column('product_display_name', sa.String(length=500), nullable=False),
    sa.Column('manufacture_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('batch_lot_number', sa.String(length=200), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'brand_cosh_id', 'batch_lot_number', name='uq_qr_pesticide'),
    sa.UniqueConstraint('client_id', 'variety_id', 'batch_lot_number', name='uq_qr_seed')
    )
    op.create_table('qr_scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('qr_code_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_user_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('scan_attempt_number', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['qr_code_id'], ['product_qr_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_scans')
    op.drop_table('product_qr_codes')
    op.drop_table('manufacturer_brand_portfolios')
    # ### end Alembic commands ###
