"""domain2_clients_onboarding

Revision ID: 76f9f17ced0f
Revises: 35f7fda69b9f
Create Date: 2026-05-01 13:09:51.998600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f9f17ced0f'
down_revision: Union[str, Sequence[str], None] = '35f7fda69b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=12), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_colour', sa.String(length=7), nullable=True),
    sa.Column('secondary_colour', sa.String(length=7), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('hq_address', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('support_phone', sa.String(length=20), nullable=True),
    sa.Column('office_phone', sa.String(length=20), nullable=True),
    sa.Column('is_manufacturer', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'ACTIVE', 'INACTIVE', 'REJECTED', name='clientstatus'), nullable=False),
    sa.Column('onboarding_link_token', sa.Text(), nullable=True),
    sa.Column('onboarding_link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('ca_name', sa.String(length=255), nullable=False),
    sa.Column('ca_phone', sa.String(length=15), nullable=False),
    sa.Column('ca_email', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('pan_number'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('cm_privileges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cm_user_id', sa.String(length=36), nullable=False),
    sa.Column('privilege', sa.Enum('CROP_HEALTH_CROPS', 'BRAND_HANDLING', 'VOLUME_CALCULATIONS', name='cmprivilege'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cm_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cm_user_id', 'privilege')
    )
    op.create_table('client_crops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('crop_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'crop_cosh_id')
    )
    op.create_table('client_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('state_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('district_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_organisation_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('org_type_cosh_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('CA', 'SUBJECT_EXPERT', 'FIELD_MANAGER', 'SEED_DATA_MANAGER', 'REPORT_USER', 'CLIENT_RM', 'PRODUCT_MANAGER', name='clientuserrole'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'user_id', 'role')
    )
    op.create_table('cm_client_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cm_user_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('rights', sa.Enum('EDIT', 'VIEW', name='cmrights'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cm_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cm_user_id', 'client_id')
    )
    op.create_table('crop_expert_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('crop_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crop_expert_assignments')
    op.drop_table('cm_client_assignments')
    op.drop_table('client_users')
    op.drop_table('client_organisation_types')
    op.drop_table('client_locations')
    op.drop_table('client_crops')
    op.drop_table('cm_privileges')
    op.drop_table('clients')
    # ### end Alembic commands ###
