"""domain3_4_advisory_cha_tables

Revision ID: 7f2742301d00
Revises: dfa40335c9b4
Create Date: 2026-05-01 14:12:14.993242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2742301d00'
down_revision: Union[str, Sequence[str], None] = 'dfa40335c9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('crop_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('package_type', sa.Enum('ANNUAL', 'PERENNIAL', name='packagetype'), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('start_date_label_cosh_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='packagestatus'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'crop_cosh_id', 'name', name='uq_package_client_crop_name')
    )
    op.create_table('parameters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crop_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source', sa.Enum('COSH', 'CUSTOM', name='parametersource'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pg_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_group_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('application_type', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('imported_from_global_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['pg_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sp_recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('specific_problem_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('application_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_authors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('professional_profile', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('state_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('district_cosh_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parameter_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('translation_status', sa.Enum('PENDING', 'APPROVED', name='translationstatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_id', 'language_code')
    )
    op.create_table('pg_timelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pg_recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('from_type', sa.String(length=30), nullable=False),
    sa.Column('from_value', sa.Integer(), nullable=False),
    sa.Column('to_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pg_recommendation_id'], ['pg_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sp_timelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sp_recommendation_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('from_type', sa.String(length=30), nullable=False),
    sa.Column('from_value', sa.Integer(), nullable=False),
    sa.Column('to_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sp_recommendation_id'], ['sp_recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('from_type', sa.Enum('DBS', 'DAS', 'CALENDAR', name='timelinefromtype'), nullable=False),
    sa.Column('from_value', sa.Integer(), nullable=False),
    sa.Column('to_value', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'name')
    )
    op.create_table('variables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parameter_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_id', 'name')
    )
    op.create_table('conditional_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_variables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('parameter_id', sa.String(length=36), nullable=False),
    sa.Column('variable_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameters.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'parameter_id')
    )
    op.create_table('pg_practices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('l0_type', sa.String(length=20), nullable=False),
    sa.Column('l1_type', sa.String(length=100), nullable=True),
    sa.Column('l2_type', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_special_input', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['pg_timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.Enum('AND', 'OR', 'IF', name='relationtype'), nullable=False),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sp_practices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('l0_type', sa.String(length=20), nullable=False),
    sa.Column('l1_type', sa.String(length=100), nullable=True),
    sa.Column('l2_type', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_special_input', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['sp_timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variable_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variable_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('translation_status', sa.Enum('PENDING', 'APPROVED', name='translationstatus'), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variable_id', 'language_code')
    )
    op.create_table('conditional_question_translations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('translation_status', sa.Enum('PENDING', 'APPROVED', name='translationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['conditional_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'language_code')
    )
    op.create_table('pg_elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('element_type', sa.String(length=100), nullable=False),
    sa.Column('cosh_ref', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('unit_cosh_id', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['pg_practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('l0_type', sa.Enum('INPUT', 'NON_INPUT', 'INSTRUCTION', 'MEDIA', name='practicel0'), nullable=False),
    sa.Column('l1_type', sa.String(length=100), nullable=True),
    sa.Column('l2_type', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.String(length=36), nullable=True),
    sa.Column('relation_role', sa.String(length=50), nullable=True),
    sa.Column('is_special_input', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['relations.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sp_elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('element_type', sa.String(length=100), nullable=False),
    sa.Column('cosh_ref', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('unit_cosh_id', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['sp_practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('element_type', sa.String(length=100), nullable=False),
    sa.Column('cosh_ref', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('unit_cosh_id', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_conditionals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('answer', sa.Enum('YES', 'NO', 'BOTH', name='conditionalanswer'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['conditional_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # VARCHAR(20) for shared status columns is intentional
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_conditionals')
    op.drop_table('elements')
    op.drop_table('sp_elements')
    op.drop_table('practices')
    op.drop_table('pg_elements')
    op.drop_table('conditional_question_translations')
    op.drop_table('variable_translations')
    op.drop_table('sp_practices')
    op.drop_table('relations')
    op.drop_table('pg_practices')
    op.drop_table('package_variables')
    op.drop_table('conditional_questions')
    op.drop_table('variables')
    op.drop_table('timelines')
    op.drop_table('sp_timelines')
    op.drop_table('pg_timelines')
    op.drop_table('parameter_translations')
    op.drop_table('package_locations')
    op.drop_table('package_authors')
    op.drop_table('sp_recommendations')
    op.drop_table('pg_recommendations')
    op.drop_table('parameters')
    op.drop_table('packages')
    # ### end Alembic commands ###
