"""domain9_farmpundit_queries

Revision ID: 9bc5043bd052
Revises: b8f71fa7e645
Create Date: 2026-05-01 14:29:16.726216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc5043bd052'
down_revision: Union[str, Sequence[str], None] = 'b8f71fa7e645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_pundit_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('experience_band', sa.String(length=30), nullable=True),
    sa.Column('support_method', sa.String(length=20), nullable=True),
    sa.Column('cultivation_type', sa.String(length=100), nullable=True),
    sa.Column('organisation_name', sa.String(length=500), nullable=True),
    sa.Column('organisation_type_cosh_id', sa.String(length=100), nullable=True),
    sa.Column('phone_hidden', sa.Boolean(), nullable=False),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('client_farm_pundits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('pundit_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('round_robin_sequence', sa.Integer(), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pundit_id'], ['farm_pundit_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'pundit_id')
    )
    op.create_table('farm_pundit_expertise',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pundit_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pundit_id'], ['farm_pundit_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_pundit_support_areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pundit_id', sa.String(length=36), nullable=False),
    sa.Column('state_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('district_cosh_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pundit_id'], ['farm_pundit_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pundit_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('pundit_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['pundit_id'], ['farm_pundit_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('crop_cosh_id', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farmer_user_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('crop_cosh_id', sa.String(length=100), nullable=True),
    sa.Column('crop_age', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('current_holder_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['current_holder_id'], ['farm_pundit_profiles.id'], ),
    sa.ForeignKeyConstraint(['farmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_remarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('pundit_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('forwarded_to_pundit_id', sa.String(length=36), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forwarded_to_pundit_id'], ['farm_pundit_profiles.id'], ),
    sa.ForeignKeyConstraint(['pundit_id'], ['farm_pundit_profiles.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_id', sa.String(length=36), nullable=False),
    sa.Column('pundit_id', sa.String(length=36), nullable=False),
    sa.Column('problem_cosh_id', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('standard_response_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pundit_id'], ['farm_pundit_profiles.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_responses')
    op.drop_table('query_remarks')
    op.drop_table('query_media')
    op.drop_table('queries')
    op.drop_table('standard_responses')
    op.drop_table('pundit_invitations')
    op.drop_table('farm_pundit_support_areas')
    op.drop_table('farm_pundit_expertise')
    op.drop_table('client_farm_pundits')
    op.drop_table('farm_pundit_profiles')
    # ### end Alembic commands ###
