"""domain6_orders

Revision ID: b8f71fa7e645
Revises: b6de4eac7872
Create Date: 2026-05-01 14:25:51.229841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f71fa7e645'
down_revision: Union[str, Sequence[str], None] = 'b6de4eac7872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_user_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('dealer_user_id', sa.String(length=36), nullable=True),
    sa.Column('facilitator_user_id', sa.String(length=36), nullable=True),
    sa.Column('date_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('locked_timelines', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['dealer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facilitator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('farmer_user_id', sa.String(length=36), nullable=False),
    sa.Column('variety_id', sa.String(length=36), nullable=False),
    sa.Column('dealer_user_id', sa.String(length=36), nullable=True),
    sa.Column('facilitator_user_id', sa.String(length=36), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('total_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facilitator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packing_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=True),
    sa.Column('seed_order_id', sa.String(length=36), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_shared_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['seed_order_id'], ['seed_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('brand_cosh_id', sa.String(length=200), nullable=True),
    sa.Column('brand_name', sa.String(length=500), nullable=True),
    sa.Column('given_volume', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('volume_unit', sa.String(length=50), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estimated_volume', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('postponed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missing_brand_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dealer_user_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('brand_name_reported', sa.String(length=500), nullable=False),
    sa.Column('manufacturer_name', sa.String(length=500), nullable=True),
    sa.Column('l2_practice', sa.String(length=100), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cm_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dealer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missing_brand_reports')
    op.drop_table('order_items')
    op.drop_table('packing_lists')
    op.drop_table('seed_orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
