"""domain11_sync_cosh_reference_cache

Revision ID: dfa40335c9b4
Revises: 76f9f17ced0f
Create Date: 2026-05-01 13:37:05.219104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa40335c9b4'
down_revision: Union[str, Sequence[str], None] = '76f9f17ced0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosh_reference_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cosh_id', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('parent_cosh_id', sa.String(length=200), nullable=True),
    sa.Column('secondary_parent_cosh_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cosh_id', 'entity_type', name='uq_cosh_ref_id_type')
    )
    op.create_index('idx_crc_entity', 'cosh_reference_cache', ['entity_type'], unique=False)
    op.create_index('idx_crc_parent', 'cosh_reference_cache', ['parent_cosh_id'], unique=False)
    op.create_index('idx_crc_status', 'cosh_reference_cache', ['entity_type', 'status'], unique=False)
    op.create_table('cosh_sync_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=200), nullable=False),
    sa.Column('initiated_by', sa.String(length=200), nullable=True),
    sa.Column('sync_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('items_synced', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop_health_crops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crop_cosh_id', sa.String(length=100), nullable=False),
    sa.Column('enabled_by', sa.String(length=36), nullable=True),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop_cosh_id')
    )
    op.create_table('volume_formulas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('measure', sa.String(length=20), nullable=False),
    sa.Column('l2_practice', sa.String(length=200), nullable=False),
    sa.Column('application_method', sa.String(length=200), nullable=False),
    sa.Column('brand_unit', sa.String(length=50), nullable=False),
    sa.Column('dosage_unit', sa.String(length=100), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # VARCHAR(20) for status is intentional — statusenum type shared via Python model
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volume_formulas')
    op.drop_table('crop_health_crops')
    op.drop_table('cosh_sync_log')
    op.drop_index('idx_crc_status', table_name='cosh_reference_cache')
    op.drop_index('idx_crc_parent', table_name='cosh_reference_cache')
    op.drop_index('idx_crc_entity', table_name='cosh_reference_cache')
    op.drop_table('cosh_reference_cache')
    # ### end Alembic commands ###
